-- Editor dei testi del sito: migrazione autonoma e idempotente.
create table if not exists public.site_page_content (
  page text not null check (page in ('home','arcani','respiro','ispirazione')),
  state text not null check (state in ('draft','published')),
  content jsonb not null,
  revision integer not null default 1 check (revision > 0),
  updated_at timestamptz not null default now(),
  primary key (page, state)
);

comment on table public.site_page_content is 'Testi strutturati delle pagine, separati tra bozza e pubblicato';

create or replace function public.site_content_spec(p_page text)
returns jsonb language sql immutable set search_path = public as $$
  select (jsonb_build_object('home', '{"hero_kicker":160,"hero_title":160,"hero_subtitle":3000,"intro_kicker":160,"intro_text":3000,"arcani_kicker":160,"arcani_title":160,"arcani_intro":3000,"arcani_item_1":500,"arcani_item_2":500,"arcani_item_3":500,"arcani_item_4":500,"arcani_item_5":500,"arcani_item_6":500,"arcani_closing":3000,"respiro_kicker":160,"respiro_title":160,"respiro_intro":3000,"respiro_group_1":160,"respiro_items_1":500,"respiro_group_2":160,"respiro_items_2":500,"respiro_closing":3000,"respiro_place":500,"respiro_note":500,"arte_kicker":160,"arte_title":160,"arte_intro":3000,"arte_group_1":160,"arte_text_1":500,"arte_group_2":160,"arte_text_2":500,"arte_group_3":160,"arte_text_3":500,"arte_group_4":160,"arte_text_4":500,"final_kicker":160,"final_title":160,"final_arcani":160,"final_respiro":160,"final_arte":160}'::jsonb, 'arcani', '{"hero_kicker":160,"hero_title":160,"hero_text":3000,"section_1_title":160,"section_1_text":3000,"section_2_title":160,"section_2_text":3000,"section_3_title":160,"section_3_text":3000,"closing":3000}'::jsonb, 'respiro', '{"hero_kicker":160,"hero_title":160,"hero_text":3000,"section_1_title":160,"section_1_text":3000,"section_2_title":160,"section_2_text":3000,"section_3_title":160,"section_3_text":3000,"section_4_title":160,"section_4_text":3000,"practical_label":160,"practical_place":160,"practical_text":3000,"closing":3000}'::jsonb, 'ispirazione', '{"hero_kicker":160,"hero_title":160,"hero_text":3000,"section_1_label":160,"section_1_title":160,"section_1_text":3000,"section_2_label":160,"section_2_title":160,"section_2_text":3000,"section_3_label":160,"section_3_title":160,"section_3_text":3000,"section_4_label":160,"section_4_title":160,"section_4_text":3000,"closing":3000}'::jsonb))->p_page;
$$;

create or replace function public.validate_site_page_content()
returns trigger language plpgsql set search_path = public as $$
declare
  spec jsonb := public.site_content_spec(new.page);
  item record;
begin
  if spec is null or jsonb_typeof(new.content) <> 'object'
    or (select count(*) from jsonb_object_keys(new.content)) <> (select count(*) from jsonb_object_keys(spec)) then
    raise exception 'Contenuto non conforme allo schema della pagina' using errcode = '22023';
  end if;
  for item in select key, value from jsonb_each(new.content) loop
    if not (spec ? item.key) or jsonb_typeof(item.value) <> 'string' then
      raise exception 'Campo non consentito o non testuale: %', item.key using errcode = '22023';
    end if;
    if btrim(item.value #>> '{}') = '' or char_length(item.value #>> '{}') > (spec->>item.key)::integer then
      raise exception 'Lunghezza non valida per il campo: %', item.key using errcode = '22023';
    end if;
    if (item.value #>> '{}') ~ '<[^>]+>' then
      raise exception 'HTML non consentito nel campo: %', item.key using errcode = '22023';
    end if;
  end loop;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists validate_site_page_content_trigger on public.site_page_content;
create trigger validate_site_page_content_trigger before insert or update of page, content on public.site_page_content
for each row execute function public.validate_site_page_content();

insert into public.site_page_content (page, state, content) values
  ('home', 'draft', '{"hero_kicker":"Un percorso con Jessica Marin","hero_title":"Le tre vie\nper illuminarsi","hero_subtitle":"Tarocchi, yoga, attività fisica e arte: tre vie per conoscerti, ritrovare equilibrio ed esprimere ciò che sei.","intro_kicker":"La Sacerdotessa","intro_text":"Sono Jessica Marin. Ti accompagno nell’esplorazione del tuo mondo interiore attraverso simboli, tarocchi e pratiche del corpo. Nei miei corsi, percorsi e workshop condivido conoscenze esoteriche, yoga e attività motorie, dai livelli di base a quelli avanzati. Vuoi trovare la tua luce interiore? Scegli la tua via.","arcani_kicker":"Il cammino attraverso i simboli","arcani_title":"La Via degli Arcani","arcani_intro":"Non solo divinazione: i tarocchi come via di conoscenza, interpretazione e consapevolezza.","arcani_item_1":"Corsi sugli Arcani Maggiori e Minori","arcani_item_2":"Metodi di stesura e lettura","arcani_item_3":"Medianità attraverso i tarocchi","arcani_item_4":"La Carta del Destino — comprendere sé e gli altri dalla data di nascita","arcani_item_5":"Esercitazioni pratiche sulle stesure — ogni primo venerdì del mese, Libreria Esoterica Il Sigillo","arcani_item_6":"Consulti personali","arcani_closing":"Ogni percorso è pensato per accompagnarti verso una comprensione più profonda del simbolo e di te stesso.","respiro_kicker":"Yoga e attività fisica","respiro_title":"La Via del Respiro","respiro_intro":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica: Yoga e attività fisica si incontrano in un percorso di ascolto, forza e consapevolezza.","respiro_group_1":"Attività fisica e pratiche dinamiche","respiro_items_1":"Power Yoga · Ginnastica Total Body","respiro_group_2":"Yoga, tecnica e respiro","respiro_items_2":"Iyengar · Hatha · Yin · Pranayama","respiro_closing":"Equilibrio tra flessibilità, forza, potenza e resistenza; atmosfera e ascolto, con chiusura di rilassamento e integrazione.","respiro_place":"Kairos Spazio Olistico — mercoledì 20:30–21:45","respiro_note":"+ sostituzioni in altre palestre","arte_kicker":"Arte, parola e contemplazione","arte_title":"La Via dell’Arte","arte_intro":"L’arte dà forma al mondo interiore: trasforma simboli, parole e ascolto in espressione e consapevolezza.","arte_group_1":"Editoriale","arte_text_1":"Articoli su simbolismo e alchimia interiore","arte_group_2":"Sonoro","arte_text_2":"Ascolti e paesaggi sonori esoterici","arte_group_3":"Letterario","arte_text_3":"Testi sacri e poesia mistica","arte_group_4":"Culturale","arte_text_4":"Eventi e progetti","final_kicker":"Il tuo prossimo passo","final_title":"Scegli la via\nche senti tua","final_arcani":"La Via degli Arcani","final_respiro":"La Via del Respiro","final_arte":"La Via dell’Arte"}'::jsonb),
  ('home', 'published', '{"hero_kicker":"Un percorso con Jessica Marin","hero_title":"Le tre vie\nper illuminarsi","hero_subtitle":"Tarocchi, yoga, attività fisica e arte: tre vie per conoscerti, ritrovare equilibrio ed esprimere ciò che sei.","intro_kicker":"La Sacerdotessa","intro_text":"Sono Jessica Marin. Ti accompagno nell’esplorazione del tuo mondo interiore attraverso simboli, tarocchi e pratiche del corpo. Nei miei corsi, percorsi e workshop condivido conoscenze esoteriche, yoga e attività motorie, dai livelli di base a quelli avanzati. Vuoi trovare la tua luce interiore? Scegli la tua via.","arcani_kicker":"Il cammino attraverso i simboli","arcani_title":"La Via degli Arcani","arcani_intro":"Non solo divinazione: i tarocchi come via di conoscenza, interpretazione e consapevolezza.","arcani_item_1":"Corsi sugli Arcani Maggiori e Minori","arcani_item_2":"Metodi di stesura e lettura","arcani_item_3":"Medianità attraverso i tarocchi","arcani_item_4":"La Carta del Destino — comprendere sé e gli altri dalla data di nascita","arcani_item_5":"Esercitazioni pratiche sulle stesure — ogni primo venerdì del mese, Libreria Esoterica Il Sigillo","arcani_item_6":"Consulti personali","arcani_closing":"Ogni percorso è pensato per accompagnarti verso una comprensione più profonda del simbolo e di te stesso.","respiro_kicker":"Yoga e attività fisica","respiro_title":"La Via del Respiro","respiro_intro":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica: Yoga e attività fisica si incontrano in un percorso di ascolto, forza e consapevolezza.","respiro_group_1":"Attività fisica e pratiche dinamiche","respiro_items_1":"Power Yoga · Ginnastica Total Body","respiro_group_2":"Yoga, tecnica e respiro","respiro_items_2":"Iyengar · Hatha · Yin · Pranayama","respiro_closing":"Equilibrio tra flessibilità, forza, potenza e resistenza; atmosfera e ascolto, con chiusura di rilassamento e integrazione.","respiro_place":"Kairos Spazio Olistico — mercoledì 20:30–21:45","respiro_note":"+ sostituzioni in altre palestre","arte_kicker":"Arte, parola e contemplazione","arte_title":"La Via dell’Arte","arte_intro":"L’arte dà forma al mondo interiore: trasforma simboli, parole e ascolto in espressione e consapevolezza.","arte_group_1":"Editoriale","arte_text_1":"Articoli su simbolismo e alchimia interiore","arte_group_2":"Sonoro","arte_text_2":"Ascolti e paesaggi sonori esoterici","arte_group_3":"Letterario","arte_text_3":"Testi sacri e poesia mistica","arte_group_4":"Culturale","arte_text_4":"Eventi e progetti","final_kicker":"Il tuo prossimo passo","final_title":"Scegli la via\nche senti tua","final_arcani":"La Via degli Arcani","final_respiro":"La Via del Respiro","final_arte":"La Via dell’Arte"}'::jsonb),
  ('arcani', 'draft', '{"hero_kicker":"Il cammino attraverso i simboli","hero_title":"La Via degli Arcani","hero_text":"La Via degli Arcani è il percorso dedicato a chi desidera entrare davvero nel linguaggio dei tarocchi, non solo come strumento divinatorio, ma come via di conoscenza, interpretazione e consapevolezza. Qui Jessica Marin accompagna l''allievo nello studio degli arcani maggiori, degli arcani minori, dei metodi di stesura, della medianità attraverso i tarocchi e della carta del destino.","section_1_title":"Corsi e percorsi sui tarocchi","section_1_text":"Il percorso include corsi dedicati agli arcani maggiori, agli arcani minori, ai metodi di stesura dei tarocchi e allo sviluppo della medianità per mezzo dei tarocchi. Ogni proposta è pensata per aiutare la persona a leggere il simbolo con più profondità, ordine e sensibilità.","section_2_title":"Carta del destino e lettura simbolica","section_2_text":"Tra i percorsi proposti c''è anche la carta del destino, un lavoro che aiuta a comprendere se stessi e gli altri attraverso la data di nascita, in una chiave simbolica e riflessiva.","section_3_title":"Esercitazioni pratiche sulle stesure dei tarocchi","section_3_text":"Ogni primo venerdì del mese, presso la Libreria Esoterica Il Sigillo, Jessica guida un incontro di esercitazione sulle stesure dei tarocchi. Questo spazio formativo aiuta gli allievi a integrare arcani maggiori e minori, imparare a porre le domande giuste e offrire un responso più chiaro, veritiero e ben strutturato.","closing":"Ogni percorso è pensato per accompagnarti verso una comprensione più profonda del simbolo e di te stesso."}'::jsonb),
  ('arcani', 'published', '{"hero_kicker":"Il cammino attraverso i simboli","hero_title":"La Via degli Arcani","hero_text":"La Via degli Arcani è il percorso dedicato a chi desidera entrare davvero nel linguaggio dei tarocchi, non solo come strumento divinatorio, ma come via di conoscenza, interpretazione e consapevolezza. Qui Jessica Marin accompagna l''allievo nello studio degli arcani maggiori, degli arcani minori, dei metodi di stesura, della medianità attraverso i tarocchi e della carta del destino.","section_1_title":"Corsi e percorsi sui tarocchi","section_1_text":"Il percorso include corsi dedicati agli arcani maggiori, agli arcani minori, ai metodi di stesura dei tarocchi e allo sviluppo della medianità per mezzo dei tarocchi. Ogni proposta è pensata per aiutare la persona a leggere il simbolo con più profondità, ordine e sensibilità.","section_2_title":"Carta del destino e lettura simbolica","section_2_text":"Tra i percorsi proposti c''è anche la carta del destino, un lavoro che aiuta a comprendere se stessi e gli altri attraverso la data di nascita, in una chiave simbolica e riflessiva.","section_3_title":"Esercitazioni pratiche sulle stesure dei tarocchi","section_3_text":"Ogni primo venerdì del mese, presso la Libreria Esoterica Il Sigillo, Jessica guida un incontro di esercitazione sulle stesure dei tarocchi. Questo spazio formativo aiuta gli allievi a integrare arcani maggiori e minori, imparare a porre le domande giuste e offrire un responso più chiaro, veritiero e ben strutturato.","closing":"Ogni percorso è pensato per accompagnarti verso una comprensione più profonda del simbolo e di te stesso."}'::jsonb),
  ('respiro', 'draft', '{"hero_kicker":"Yoga e attività fisica","hero_title":"La Via del Respiro","hero_text":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica: Yoga e attività fisica si incontrano in un percorso di ascolto, forza e consapevolezza.","section_1_title":"Attività fisica e pratiche dinamiche","section_1_text":"Power Yoga e Ginnastica Total Body sviluppano movimento, energia, forza e resistenza attraverso una pratica consapevole e progressiva.","section_2_title":"Yoga, tecnica e respiro","section_2_text":"Iyengar, Hatha, Yin e Pranayama uniscono precisione, ascolto e respirazione per accompagnare ogni persona verso una pratica più profonda.","section_3_title":"Ascolto, forza e consapevolezza","section_3_text":"La pratica diventa un percorso concreto di relazione con il corpo e la mente, adattabile ai diversi livelli e orientato a una crescita graduale.","section_4_title":"Un approccio che unisce forza e presenza","section_4_text":"Jessica non guida solo al rilassamento, ma porta la persona verso un equilibrio tra flessibilità, forza, potenza, resistenza, atmosfera e ascolto. Ogni lezione custodisce il ricordo del respiro, una cura per l''ambiente e un momento finale di rilassamento e integrazione.","practical_label":"Dove e quando","practical_place":"Kairos Spazio Olistico","practical_text":"Le lezioni si tengono attualmente presso Kairos Spazio Olistico il mercoledì sera, dalle 20:30 alle 21:45, oltre a eventuali sostituzioni in altre palestre.","closing":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica."}'::jsonb),
  ('respiro', 'published', '{"hero_kicker":"Yoga e attività fisica","hero_title":"La Via del Respiro","hero_text":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica: Yoga e attività fisica si incontrano in un percorso di ascolto, forza e consapevolezza.","section_1_title":"Attività fisica e pratiche dinamiche","section_1_text":"Power Yoga e Ginnastica Total Body sviluppano movimento, energia, forza e resistenza attraverso una pratica consapevole e progressiva.","section_2_title":"Yoga, tecnica e respiro","section_2_text":"Iyengar, Hatha, Yin e Pranayama uniscono precisione, ascolto e respirazione per accompagnare ogni persona verso una pratica più profonda.","section_3_title":"Ascolto, forza e consapevolezza","section_3_text":"La pratica diventa un percorso concreto di relazione con il corpo e la mente, adattabile ai diversi livelli e orientato a una crescita graduale.","section_4_title":"Un approccio che unisce forza e presenza","section_4_text":"Jessica non guida solo al rilassamento, ma porta la persona verso un equilibrio tra flessibilità, forza, potenza, resistenza, atmosfera e ascolto. Ogni lezione custodisce il ricordo del respiro, una cura per l''ambiente e un momento finale di rilassamento e integrazione.","practical_label":"Dove e quando","practical_place":"Kairos Spazio Olistico","practical_text":"Le lezioni si tengono attualmente presso Kairos Spazio Olistico il mercoledì sera, dalle 20:30 alle 21:45, oltre a eventuali sostituzioni in altre palestre.","closing":"La pratica è il luogo in cui il corpo ricorda ciò che la mente dimentica."}'::jsonb),
  ('ispirazione', 'draft', '{"hero_kicker":"Arte, parola e contemplazione","hero_title":"La Via dell’Arte","hero_text":"L’arte dà forma al mondo interiore: trasforma simboli, parole e ascolto in espressione e consapevolezza.","section_1_label":"editoriale","section_1_title":"Articoli e riflessioni","section_1_text":"Scritti contemplativi su simbolismo, alchimia interiore e le correnti invisibili che attraversano l''esistenza. Uno spazio di pensiero lento e profondo.","section_2_label":"sonoro","section_2_title":"Musica e ascolti","section_2_text":"Ascolti curati, paesaggi sonori esoterici e musica che risveglia la dimensione sacra del sentire. Un invito a fermarsi e lasciarsi attraversare dal suono.","section_3_label":"letterario","section_3_title":"Letteratura esoterica","section_3_text":"Una biblioteca vivente di testi sacri, poesia mistica e opere che illuminano il cammino interiore. Letture scelte per nutrire la ricerca personale.","section_4_label":"culturale","section_4_title":"Eventi culturali e progetti speciali","section_4_text":"Incontri, collaborazioni e iniziative che uniscono arte, simbolo e comunità. Progetti che nascono dall''incontro tra visione interiore e creazione condivisa.","closing":"L’arte rende visibile ciò che il mondo interiore custodisce ancora senza forma."}'::jsonb),
  ('ispirazione', 'published', '{"hero_kicker":"Arte, parola e contemplazione","hero_title":"La Via dell’Arte","hero_text":"L’arte dà forma al mondo interiore: trasforma simboli, parole e ascolto in espressione e consapevolezza.","section_1_label":"editoriale","section_1_title":"Articoli e riflessioni","section_1_text":"Scritti contemplativi su simbolismo, alchimia interiore e le correnti invisibili che attraversano l''esistenza. Uno spazio di pensiero lento e profondo.","section_2_label":"sonoro","section_2_title":"Musica e ascolti","section_2_text":"Ascolti curati, paesaggi sonori esoterici e musica che risveglia la dimensione sacra del sentire. Un invito a fermarsi e lasciarsi attraversare dal suono.","section_3_label":"letterario","section_3_title":"Letteratura esoterica","section_3_text":"Una biblioteca vivente di testi sacri, poesia mistica e opere che illuminano il cammino interiore. Letture scelte per nutrire la ricerca personale.","section_4_label":"culturale","section_4_title":"Eventi culturali e progetti speciali","section_4_text":"Incontri, collaborazioni e iniziative che uniscono arte, simbolo e comunità. Progetti che nascono dall''incontro tra visione interiore e creazione condivisa.","closing":"L’arte rende visibile ciò che il mondo interiore custodisce ancora senza forma."}'::jsonb)
on conflict (page, state) do nothing;

alter table public.site_page_content enable row level security;
drop policy if exists "Published site content is public" on public.site_page_content;
create policy "Published site content is public" on public.site_page_content for select
using (state = 'published' or (select public.is_admin()));

revoke insert, update, delete on public.site_page_content from anon, authenticated;
grant select on public.site_page_content to anon, authenticated;

create or replace function public.save_site_content_draft(p_page text, p_content jsonb, p_expected_revision integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare current_row public.site_page_content;
begin
  if not public.is_admin() then raise exception 'Accesso amministratore richiesto' using errcode = '42501'; end if;
  select * into current_row from public.site_page_content where page = p_page and state = 'draft' for update;
  if not found or current_row.revision <> p_expected_revision then raise exception 'Conflitto: la bozza è stata modificata in un’altra sessione' using errcode = '40001'; end if;
  update public.site_page_content set content = p_content, revision = revision + 1 where page = p_page and state = 'draft' returning * into current_row;
  return to_jsonb(current_row);
end;
$$;

create or replace function public.publish_site_content(p_page text, p_expected_draft_revision integer, p_expected_published_revision integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare draft_row public.site_page_content; published_row public.site_page_content;
begin
  if not public.is_admin() then raise exception 'Accesso amministratore richiesto' using errcode = '42501'; end if;
  select * into draft_row from public.site_page_content where page = p_page and state = 'draft' for update;
  select * into published_row from public.site_page_content where page = p_page and state = 'published' for update;
  if draft_row.revision <> p_expected_draft_revision or published_row.revision <> p_expected_published_revision then raise exception 'Conflitto: i contenuti sono cambiati in un’altra sessione' using errcode = '40001'; end if;
  update public.site_page_content set content = draft_row.content, revision = revision + 1 where page = p_page and state = 'published' returning * into published_row;
  return jsonb_build_object('draft', to_jsonb(draft_row), 'published', to_jsonb(published_row));
end;
$$;

create or replace function public.restore_site_content_draft(p_page text, p_expected_draft_revision integer, p_expected_published_revision integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare draft_row public.site_page_content; published_row public.site_page_content;
begin
  if not public.is_admin() then raise exception 'Accesso amministratore richiesto' using errcode = '42501'; end if;
  select * into draft_row from public.site_page_content where page = p_page and state = 'draft' for update;
  select * into published_row from public.site_page_content where page = p_page and state = 'published' for update;
  if draft_row.revision <> p_expected_draft_revision or published_row.revision <> p_expected_published_revision then raise exception 'Conflitto: i contenuti sono cambiati in un’altra sessione' using errcode = '40001'; end if;
  update public.site_page_content set content = published_row.content, revision = revision + 1 where page = p_page and state = 'draft' returning * into draft_row;
  return to_jsonb(draft_row);
end;
$$;

revoke all on function public.save_site_content_draft(text, jsonb, integer) from public, anon;
revoke all on function public.publish_site_content(text, integer, integer) from public, anon;
revoke all on function public.restore_site_content_draft(text, integer, integer) from public, anon;
grant execute on function public.save_site_content_draft(text, jsonb, integer) to authenticated;
grant execute on function public.publish_site_content(text, integer, integer) to authenticated;
grant execute on function public.restore_site_content_draft(text, integer, integer) to authenticated;
